<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View details here</name>
   <tag></tag>
   <elementGuidId>4fa245cd-3e5c-4869-9985-16398cad0d12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-iitm-content']/div/div[3]/div/div/div/div/div/p[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.readmore__btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;View details here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ccc3d04-2761-4847-bfb7-e7c4e018b9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>readmore__btn</value>
      <webElementGuid>5cb17dc6-d160-45d6-ad16-ca8c1a1aed32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://study.iitm.ac.in</value>
      <webElementGuid>47ca04a5-a065-4bc6-81e6-0ce7cb333d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>b6b7628c-e8e8-4977-bd85-30aebd762f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View details here</value>
      <webElementGuid>3aae1bd2-634c-4e46-ba2e-4d73be7827f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details here</value>
      <webElementGuid>1f7e89b1-bad1-40fa-9043-7414c1feeffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-iitm-content&quot;)/div[@class=&quot;content block-content&quot;]/div[@class=&quot;content__page layout layout--onecol&quot;]/div[@class=&quot;layout__region layout__region--content&quot;]/div[1]/div[@class=&quot;content block-content&quot;]/div[@class=&quot;lbk-rich-text-component container&quot;]/div[@class=&quot;content block-content&quot;]/p[@class=&quot;text-center font__fontrols__style&quot;]/a[@class=&quot;readmore__btn&quot;]</value>
      <webElementGuid>729d0e75-7248-4432-ae0b-e8a7ff337be8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-iitm-content']/div/div[3]/div/div/div/div/div/p[4]/a</value>
      <webElementGuid>a4cc796b-3f0b-461a-b83d-14ae6bd8cdaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View details here')]</value>
      <webElementGuid>3b575fbe-c5f3-4456-bf49-16c73d4e9a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diploma (Programming), Diploma (Data Science), BSc (Programming and Data Science)'])[1]/following::a[1]</value>
      <webElementGuid>10204849-316c-44de-9645-9e9dded80876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='swayam.gov.in'])[1]/following::a[1]</value>
      <webElementGuid>12a5305f-aefb-4f49-bb75-bee5f5fa6f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Broken clouds'])[1]/preceding::a[2]</value>
      <webElementGuid>696aaad5-0369-4390-95eb-dfef087ff3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/preceding::a[3]</value>
      <webElementGuid>695696ae-8a28-4c1d-94b0-ef0338173dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View details here']/parent::*</value>
      <webElementGuid>1fc428e3-0632-49a9-80e2-3aeb2f450b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://study.iitm.ac.in')]</value>
      <webElementGuid>907c696c-53e0-42ce-8e8f-35c6d1e68617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/a</value>
      <webElementGuid>5be89919-1464-439e-962e-482089140c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://study.iitm.ac.in' and @title = 'View details here' and (text() = 'View details here' or . = 'View details here')]</value>
      <webElementGuid>2d0e36fe-290b-438c-b620-d136544ace79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
