<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mandatory Requirements</name>
   <tag></tag>
   <elementGuidId>0d8541d5-0b77-4447-a580-016b4b80f54f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar-default']/ul/li[2]/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Mandatory Requirements&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ff0bb164-5c40-49fd-8a37-703d5bdf1ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>645690d8-b764-46e7-b06b-9e1f9170a745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>admissions.html#AD1</value>
      <webElementGuid>07c7dc43-920f-4fb6-bbef-1eb4566426a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mandatory Requirements</value>
      <webElementGuid>f6c7104c-ef57-494c-9698-eac3eff5c493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-default&quot;)/ul[@class=&quot;navbar-nav ml-lg-auto&quot;]/li[@class=&quot;nav-item mr-0 dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-left show&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>dc326d12-6266-4ccf-ad27-e15f5ae54244</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar-default']/ul/li[2]/div/a[2]</value>
      <webElementGuid>b23c2b7d-81e1-4816-b099-a807f8ed2129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mandatory Requirements')]</value>
      <webElementGuid>6eacb4c3-695c-4949-b4f1-c46df0beaa5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Important Dates'])[1]/following::a[1]</value>
      <webElementGuid>584102a1-7223-4341-a84f-c05ae97fce93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admissions'])[1]/following::a[2]</value>
      <webElementGuid>d72ae5be-cf2c-4c9d-8527-b7dec16c922c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eligibility to Apply'])[1]/preceding::a[1]</value>
      <webElementGuid>85718ed2-b3ad-4d8c-b9d8-da6b28553899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Process'])[1]/preceding::a[2]</value>
      <webElementGuid>56eee7a3-422b-496c-9cff-9b637e881a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mandatory Requirements']/parent::*</value>
      <webElementGuid>28f5eb95-78db-4872-9621-336e585c2218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'admissions.html#AD1')]</value>
      <webElementGuid>6dd00f76-e874-4a2d-8ae9-01a9dead4233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a[2]</value>
      <webElementGuid>7125d1f9-6b0e-4179-9484-8deca89cfa3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'admissions.html#AD1' and (text() = 'Mandatory Requirements' or . = 'Mandatory Requirements')]</value>
      <webElementGuid>fdf82961-5536-479b-af53-ebe3d1d51729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
