<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Naga Phani Aetukuri_wp-image-33768</name>
   <tag></tag>
   <elementGuidId>bb1ebe03-d71a-4514-bca6-4d8537bc59d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='et-boc']/div/div/div[2]/div/div[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.wp-image-33768</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Sheetal Jain&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ccb2d573-c2da-4003-bb3b-c9779f5af291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>e69885a3-b7f4-42e2-b4b6-342cdfd79194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>d2b1c2c7-f26c-4718-858a-08645474314f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>1025e228-c1af-49ff-b950-32dadcf5c2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://sscu.iisc.ac.in/wp-content/uploads/2021/06/toc.jpg</value>
      <webElementGuid>d73ce096-36dc-4fb7-96b8-d05dacdad5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sheetal Jain</value>
      <webElementGuid>8b62d65a-4ff2-42ca-8c8e-2e1f8dbe4e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://sscu.iisc.ac.in/wp-content/uploads/2021/06/toc.jpg 300w, https://sscu.iisc.ac.in/wp-content/uploads/2021/06/toc-150x150.jpg 150w, https://sscu.iisc.ac.in/wp-content/uploads/2021/06/toc-260x260.jpg 260w, https://sscu.iisc.ac.in/wp-content/uploads/2021/06/toc-45x45.jpg 45w</value>
      <webElementGuid>128b18f9-8ba2-4736-bb87-156429c547b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>7552a7db-70b0-498e-a78e-41fb4dba10a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-image-33768</value>
      <webElementGuid>081fd4d1-d823-482a-8a8b-41dd83e811c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;et-boc&quot;)/div[@class=&quot;et-l et-l--post&quot;]/div[@class=&quot;et_builder_inner_content et_pb_gutters2&quot;]/div[@class=&quot;et_pb_section et_pb_section_1 et_pb_with_background et_section_regular&quot;]/div[@class=&quot;et_pb_row et_pb_row_1 et_pb_equal_columns et_pb_row_4col&quot;]/div[@class=&quot;et_pb_column et_pb_column_1_4 et_pb_column_3  et_pb_css_mix_blend_mode_passthrough&quot;]/div[@class=&quot;et_pb_module et_pb_team_member et_pb_team_member_1 b3_team et_clickable clearfix  et_pb_text_align_center et_pb_bg_layout_light&quot;]/div[@class=&quot;et_pb_team_member_image et_pb_animation_off et-animated et_had_animation&quot;]/img[@class=&quot;wp-image-33768&quot;]</value>
      <webElementGuid>428e5702-7cc2-4969-932f-d0a0537c0867</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='et-boc']/div/div/div[2]/div/div[2]/div/div/img</value>
      <webElementGuid>77447f42-83cc-4864-b850-8558a11a0e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sheetal Jain']</value>
      <webElementGuid>28a8045d-82de-46bf-9438-54602dbda49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>de7e71c9-6d26-4a9a-9412-80ae3bcc94ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://sscu.iisc.ac.in/wp-content/uploads/2021/06/toc.jpg' and @alt = 'Sheetal Jain']</value>
      <webElementGuid>99fe9864-b9cd-4481-b7dc-0e4065e51574</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
