<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Architecture</name>
   <tag></tag>
   <elementGuidId>aec812eb-7ed0-44ae-a8ea-b7f9894da7c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Architecture')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.inlink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Architecture&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f3c64753-d99f-4fbd-97fb-dfbff32900ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>architecture_engineering.php</value>
      <webElementGuid>fea6d8c0-f7f4-4bd2-b887-e6e768d56b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inlink</value>
      <webElementGuid>1e2b8274-cdb7-4a30-a9bb-98e047d7bda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Architecture</value>
      <webElementGuid>7a8c29dc-b975-460e-972f-01ff43299d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[5]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;bodytxt&quot;]/tbody[1]/tr[2]/td[3]/a[@class=&quot;inlink&quot;]</value>
      <webElementGuid>a9ee43ef-9566-4c6d-b3fb-34d29d7f2a8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Architecture')]</value>
      <webElementGuid>7aab9ca5-ed09-4248-8523-68df70364a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biotechnology'])[1]/preceding::a[1]</value>
      <webElementGuid>3ab528ba-4814-4ae8-91cd-476b5683b0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Civil Engineering'])[1]/preceding::a[2]</value>
      <webElementGuid>95c5706d-6bbb-4a47-9a63-5ef3179b30c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Architecture']/parent::*</value>
      <webElementGuid>5cb7caab-4e1f-4a81-9b32-d05a0cbca658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'architecture_engineering.php')]</value>
      <webElementGuid>52aec7a0-273d-4b47-bc4c-b92a6d82ee05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/a</value>
      <webElementGuid>a79c3973-2e96-410d-9738-b07e91113b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'architecture_engineering.php' and (text() = 'Architecture' or . = 'Architecture')]</value>
      <webElementGuid>fb8a4dde-a5e0-49f7-92ca-6283caa0e094</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
