<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Facilities</name>
   <tag></tag>
   <elementGuidId>318b07e1-69f6-422a-b870-e081a64b44a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='http://cet.edu.in/view_notice_details.php?recid=450'])[1]/following::td[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>table.rgtmenu > tbody > tr:nth-of-type(2) > td:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Facilities&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e2276e30-4b81-4ef4-956b-926985b14c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>65%</value>
      <webElementGuid>5000d754-dd9b-4340-800c-7d92b7917e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>12f89f47-0574-4583-a775-96882d413e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bgcolor</name>
      <type>Main</type>
      <value>#2f2f2f</value>
      <webElementGuid>9bc8c915-ee4c-4246-91d5-00b4a88cc412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Facilities</value>
      <webElementGuid>2513f15d-b567-44e6-9957-68f7e4664067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[3]/td[@class=&quot;rightmnubak&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rgtmenu&quot;]/tbody[1]/tr[2]/td[2]</value>
      <webElementGuid>1fc9259b-56a9-4fbe-bf57-bd56ea55522a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='http://cet.edu.in/view_notice_details.php?recid=450'])[1]/following::td[11]</value>
      <webElementGuid>e008c369-ef74-4e1c-84d8-b99629295e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annual Report:-'])[2]/following::td[11]</value>
      <webElementGuid>8c1506e5-bf00-492c-81a8-0deb647ffc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEQIP'])[1]/preceding::td[3]</value>
      <webElementGuid>524bed40-fcce-4c70-bc2e-baa7b6c734a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>073c4c4b-2ca7-4260-aa1f-f976857a0cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Facilities' or . = 'Facilities')]</value>
      <webElementGuid>b85cbbc6-3cd0-4305-b56f-c2acee34619f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
