<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Tenders RFQ EOI</name>
   <tag></tag>
   <elementGuidId>b7c8bf83-6458-4702-9a7f-8c54f2a37495</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Placement'])[1]/following::td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>table.rgtmenu > tbody > tr:nth-of-type(11) > td:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Tenders/ RFQ/ EOI&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1a1f603a-7323-4bff-9304-1ed5bd47c6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>2246b2fd-7e6e-4129-a7a5-bbf11efe13d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>b6c68498-dfd9-4ce0-bd48-26c9fde37f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bgcolor</name>
      <type>Main</type>
      <value>#2f2f2f</value>
      <webElementGuid>5052ed75-485f-47c1-81d5-94adb8939877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tenders/ RFQ/ EOI</value>
      <webElementGuid>eec45a6a-4209-4676-8b93-bda5bf564abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[3]/td[@class=&quot;rightmnubak&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;rgtmenu&quot;]/tbody[1]/tr[11]/td[2]</value>
      <webElementGuid>a0c99941-3cb9-4a9b-ac3c-683e72a96d86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placement'])[1]/following::td[4]</value>
      <webElementGuid>588eacd5-ad4d-4564-ab2b-c0f7f1029e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admission'])[1]/following::td[8]</value>
      <webElementGuid>1c69a9e9-ec98-4815-964e-477a3d727028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Careers'])[1]/preceding::td[4]</value>
      <webElementGuid>0fd411b9-01af-4ff5-9459-4b8c57879ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td/table/tbody/tr[11]/td[2]</value>
      <webElementGuid>043843ab-3f2d-4902-b53f-18bbe26cb980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Tenders/ RFQ/ EOI' or . = 'Tenders/ RFQ/ EOI')]</value>
      <webElementGuid>6c2fc374-9755-4edb-adad-da7ea29b14c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
