<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_About IITM_fas fa-angle-down</name>
   <tag></tag>
   <elementGuidId>f689f189-b2e1-42a8-8567-a893bfb587b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar-default']/ul/li[5]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;About IITM &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6d57c9bc-83a2-408f-9cf9-5999465b1c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-angle-down</value>
      <webElementGuid>b08450ae-a845-4243-80b9-166e4e1b34ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-default&quot;)/ul[@class=&quot;navbar-nav ml-lg-auto&quot;]/li[@class=&quot;dropdown nav-item mr-0&quot;]/a[@class=&quot;nav-link&quot;]/i[@class=&quot;fas fa-angle-down&quot;]</value>
      <webElementGuid>d4b27ce8-70e0-4a86-8abe-40b73dfdd11c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar-default']/ul/li[5]/a/i</value>
      <webElementGuid>b00cbd96-5727-417d-bfdf-10eb29b4c308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/i</value>
      <webElementGuid>826af1fd-4857-4085-ab93-1cbb12656498</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
