<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_As shared on Social Media_imgTemplate</name>
   <tag></tag>
   <elementGuidId>0e42132d-ad9c-4fe7-8aba-9c9e9ab61708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productCard-5']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productCard-5 > img.imgTemplate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#productCard-5 >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3b2f17c4-1252-440c-8ad2-dd1559140f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgTemplate</value>
      <webElementGuid>191e06e8-4f26-4c4c-b261-9460f8b06885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.imprzd.com/BroadcastImpression/api/file/displayImageV2/L2hvbWUvZWZzZGF0YS82NV9zZXJ2ZXIvcG9zdEltYWdlLzIwMjQvNS8xOS8yMDI0MDUxOTA0Mjg1MzAzMTEucG5n</value>
      <webElementGuid>a3bf15b0-4f32-4ca1-b798-d41807300dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>d2746bf3-9a14-488c-8c9a-949a648a663c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>6d4fdb51-0066-446a-aaa0-49883f8598b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt-text</name>
      <type>Main</type>
      <value>User says After a college degree, equip yourself for the future with this comprehensive data science course.&#xd; Strengthen your foothold in the data science industry by enhancing your employability through this program.&#xd;  about IITM BS, Highlights: Employability</value>
      <webElementGuid>41d345dc-7ad3-4c7e-8603-79223ed78b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productCard-5&quot;)/img[@class=&quot;imgTemplate&quot;]</value>
      <webElementGuid>b7f5adeb-364a-4ef5-b885-df043d6eb554</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productCard-5']/img</value>
      <webElementGuid>f53564f8-688b-4c8f-995c-f24dee34a75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.imprzd.com/BroadcastImpression/api/file/displayImageV2/L2hvbWUvZWZzZGF0YS82NV9zZXJ2ZXIvcG9zdEltYWdlLzIwMjQvNS8xOS8yMDI0MDUxOTA0Mjg1MzAzMTEucG5n')]</value>
      <webElementGuid>5c30a350-e573-43dd-ada0-14dcf38cd2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[5]/img</value>
      <webElementGuid>feb15103-3055-4b32-a3b3-8eeafbd449e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.imprzd.com/BroadcastImpression/api/file/displayImageV2/L2hvbWUvZWZzZGF0YS82NV9zZXJ2ZXIvcG9zdEltYWdlLzIwMjQvNS8xOS8yMDI0MDUxOTA0Mjg1MzAzMTEucG5n']</value>
      <webElementGuid>46d69100-44ce-464a-8c28-3ba66b0fbe6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
