<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_As shared on Social Media_imgTemplate_1</name>
   <tag></tag>
   <elementGuidId>e46b97aa-e938-49fc-bb8d-be9d42ebfd78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productCard-8']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productCard-8 > img.imgTemplate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#productCard-8 >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>15a6a6db-a2a4-4e99-9365-04bef7e16873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgTemplate</value>
      <webElementGuid>8235b464-fb90-4fe1-9fbe-3595f8a26f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.imprzd.com/BroadcastImpression/api/file/displayImageV2/L2hvbWUvZWZzZGF0YS82NV9zZXJ2ZXIvcG9zdEltYWdlLzIwMjQvNS8xNy8yMDI0MDUxNzA1NDEwNjA0OTEucG5n</value>
      <webElementGuid>7103f691-ced0-49fa-b43e-0ad099cdd669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>4ae66873-aa7c-46a2-8c53-3b08c544cf7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>83c84879-9dd4-4173-bcac-73854beaece4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt-text</name>
      <type>Main</type>
      <value>User says The prospect of learning data modeling ignites a passion within me for continuous knowledge and growth.&#xd; I am thrilled at the thought of this course being the key to unlocking diverse career opportunities for me.&#xd;  about IITM BS, Highlights: Career opportunities</value>
      <webElementGuid>1b388a7f-c180-40e4-b235-715287d34c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productCard-8&quot;)/img[@class=&quot;imgTemplate&quot;]</value>
      <webElementGuid>6a3cc5b9-1855-4143-8e10-f05c26fbd608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productCard-8']/img</value>
      <webElementGuid>e59c1493-0dc6-4534-9c00-4a5b4965b07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.imprzd.com/BroadcastImpression/api/file/displayImageV2/L2hvbWUvZWZzZGF0YS82NV9zZXJ2ZXIvcG9zdEltYWdlLzIwMjQvNS8xNy8yMDI0MDUxNzA1NDEwNjA0OTEucG5n')]</value>
      <webElementGuid>a55d00d8-b62b-410f-92c5-63dc2b6d5598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/img</value>
      <webElementGuid>634c0dae-3160-4b66-9eb1-5ec70f095b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.imprzd.com/BroadcastImpression/api/file/displayImageV2/L2hvbWUvZWZzZGF0YS82NV9zZXJ2ZXIvcG9zdEltYWdlLzIwMjQvNS8xNy8yMDI0MDUxNzA1NDEwNjA0OTEucG5n']</value>
      <webElementGuid>c5ae10dc-82eb-439b-81e7-c159d3690f9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
