<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_No results found_imprzdModalImageContainer</name>
   <tag></tag>
   <elementGuidId>60ef6081-8265-488c-90f6-132a93a4e3fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='imprzdParentModal1']/div/div/div[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.imprzdModalImageContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Template 8&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3556b8d0-d3b1-4018-9744-f5fcd1114345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.imprzd.com/BroadcastImpression/api/file/displayImageV2/L2hvbWUvZWZzZGF0YS82NV9zZXJ2ZXIvcG9zdEltYWdlLzIwMjQvNS8xNy8yMDI0MDUxNzA1NDEwNjA0OTEucG5n</value>
      <webElementGuid>a7f1563f-ad19-4a0d-ad5b-5a66b2172d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Template 8</value>
      <webElementGuid>294e3364-3342-43d1-a844-e20b99da7df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imprzdModalImageContainer</value>
      <webElementGuid>bab4a44d-7fde-4947-ad36-fbd05249f970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imprzdParentModal1&quot;)/div[@class=&quot;imprzdChildModal&quot;]/div[@class=&quot;imprzdModalContent&quot;]/div[@class=&quot;imprzdImageCloseModal&quot;]/div[1]/img[@class=&quot;imprzdModalImageContainer&quot;]</value>
      <webElementGuid>404c8094-9765-4ff8-814a-9abedecd91d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='imprzdParentModal1']/div/div/div[2]/div/img</value>
      <webElementGuid>3b5c35cd-559a-4f94-9aad-95da8ebc0ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Template 8']</value>
      <webElementGuid>5f1908f7-43e8-455b-b445-e6f5d635e4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/img</value>
      <webElementGuid>e5da89c8-119e-41d5-a73e-40381819ca8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.imprzd.com/BroadcastImpression/api/file/displayImageV2/L2hvbWUvZWZzZGF0YS82NV9zZXJ2ZXIvcG9zdEltYWdlLzIwMjQvNS8xNy8yMDI0MDUxNzA1NDEwNjA0OTEucG5n' and @alt = 'Template 8']</value>
      <webElementGuid>e87881b9-2aa8-458a-ba5c-77793f60b14d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
