<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Research</name>
   <tag></tag>
   <elementGuidId>fd6f538b-51c4-423d-82e1-91ce248d78c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ubermenu-nav-main-3']/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ubermenu-nav-main-3 > li.ubermenu-item.ubermenu-item-type-post_type.ubermenu-item-object-page.ubermenu-item-32892.ubermenu-item-level-0.ubermenu-column.ubermenu-column-auto > a.ubermenu-target.ubermenu-item-layout-default.ubermenu-item-layout-text_only</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Research&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f9591275-3faa-44c6-82cf-3b3ab4ad32d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only</value>
      <webElementGuid>6029b919-7a19-4828-98c1-24a8dd9ccf1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sscu.iisc.ac.in/research/</value>
      <webElementGuid>bce3d8be-d6c2-4061-a1e0-2560794d153d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7426716a-1601-43c3-ada9-e54805db0dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Research</value>
      <webElementGuid>84c5201a-72ff-41e1-8a7a-4387aa9a1a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ubermenu-nav-main-3&quot;)/li[@class=&quot;ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-32892 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto&quot;]/a[@class=&quot;ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only&quot;]</value>
      <webElementGuid>a80d0424-81bc-4549-98fa-8699ff222da4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ubermenu-nav-main-3']/li[3]/a</value>
      <webElementGuid>10b89840-0a71-4292-892d-44565451d346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[3]/following::a[1]</value>
      <webElementGuid>0a04ad63-6d24-4383-95ea-252fa33a87e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumni'])[2]/following::a[1]</value>
      <webElementGuid>c5179fc9-165c-44f9-96e0-c59f066f5cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prospective Faculty'])[2]/preceding::a[1]</value>
      <webElementGuid>18ed1b0d-e141-4757-b2cb-130768ebca10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://sscu.iisc.ac.in/research/')])[2]</value>
      <webElementGuid>98be26f5-0d5d-4d7f-b3c1-92dc351b2a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/nav/ul/li[3]/a</value>
      <webElementGuid>e85bf7ff-9f0f-46ef-bd71-c5459a78815a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sscu.iisc.ac.in/research/' and (text() = 'Research' or . = 'Research')]</value>
      <webElementGuid>d4360c84-c2fe-4643-aed3-0001e37ca58f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
